try:
    a=10/0;
    print("Exception occurred")
finally:
    print("Code to be executed")